name: Build Android Zips
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  app_id: pvr.ultimate

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - kodi-branch: Nexus
            host: aarch64-linux-android
          - kodi-branch: Nexus
            host: arm-linux-androideabi
          - kodi-branch: Omega
            host: aarch64-linux-android
          - kodi-branch: Omega
            host: arm-linux-androideabi
          - kodi-branch: master
            host: aarch64-linux-android
          - kodi-branch: master
            host: arm-linux-androideabi

    steps:
      - name: Checkout Add-on Repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.app_id }}

      - name: Build Add-on
        uses: xbmc/action-build-addon@v2
        with:
          kodi_branch: ${{ matrix.kodi-branch }}
          kodi_repo: xbmc/xbmc
          addon_id: ${{ env.app_id }}
          addon_path: ${{ github.workspace }}/${{ env.app_id }}
          host: ${{ matrix.host }}

      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pvr.ultimate-android-${{ matrix.kodi-branch }}-${{ matrix.host }}
          path: ${{ env.app_id }}/build/zips/*.zip